### ISSUE TITLE
_mxLogger.setMaxDiskSize(1024 * 1024 * 10); 设置后没效果

### ISSUE THREAD

**Issue by zilanfeng** [coder-dongjiayi/MXLogger#10]
日志文件超过10M了，文件大小还在继续增加

**Comment by coder-dongjiayi** [comment]
默认情况下会在app进入后台的时候进行清理数据。你尝试一下 app进入后台 然后看一下控制台的输出

**Comment by zilanfeng** [comment]
刚才用这个demo试了下，放后台也没有清理数据再回来 没有清理数据，重新运行app都没用，超过10M了 还可以继续写入日志

**Comment by coder-dongjiayi** [comment]
setMaxDiskAge和setMaxDiskSize 是不会清理当前正在写入的文件，这是由于mmap这种映射机制导致的，一旦删除当前映射的磁盘文件，就无法写入数据了。setMaxDiskAge和setMaxDiskSize 这两个方法只对历史数据生效。你可以调整手机时间 重启app以生多个日志文件 进行测试，如果你用模拟器的话可以直接往沙盒目录拷贝日志文件 进行测试。

**Comment by zilanfeng** [comment]
ok 感谢回复
期待日志压缩到一个文件早日上线
<img width="430" alt="image" src="https://user-images.githubusercontent.com/8188626/234164714-2b828ab7-5d29-4674-b1ea-35adde105215.png">

**Comment by coder-dongjiayi** [comment]
> ok 感谢回复 期待日志压缩到一个文件早日上线 <img alt="image" width="430" src="https://user-images.githubusercontent.com/8188626/234164714-2b828ab7-5d29-4674-b1ea-35adde105215.png">

这段时间时间特别忙，争取今年能上线。
