### ISSUE TITLE
 load dynamic library 'libmxlogger.so' failed

### ISSUE THREAD

**Issue by aniealss** [coder-dongjiayi/MXLogger#12]
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Invalid argument(s): Failed to load dynamic library 'libmxlogger.so': dlopen failed: library "libmxlogger.so" not found. Error thrown Instance of 'ErrorDescription'.

new DynamicLibrary.open (dart:ffi)
._nativeLib (flutter_mxlogger.dart:473)
._removeExpireData (flutter_mxlogger.dart)
MXLogger.removeExpireData (flutter_mxlogger.dart)
MXLogger.didChangeAppLifecycleState (flutter_mxlogger.dart:76)

**Comment by coder-dongjiayi** [comment]
能重现么，版本号是多少

**Comment by aniealss** [comment]
flutter_mxlogger: ^1.2.5+6

线上用户这个报错很多，自己测试没有复现

**Comment by coder-dongjiayi** [comment]
> 

报这个错误的设备机型 firebase 能看到么

**Comment by aniealss** [comment]
Samsung
Galaxy J7
Galaxy J2
Galaxy J2 Pro

Vivo
Y55s
Y53
Y21L

Oppo
A1601
CPH1701
A37

Xiaomi
Redmi Note 4
Redmi 4 Pro
Redmi 4A

这些是靠前的几个

**Comment by coder-dongjiayi** [comment]
我买了一个Galaxy J7008，我调低了minSdkVersion = 16 才可以进行调试，但是我并没有复现这个问题。不过我发现了一些其他的问题我买的这个 Galaxy J7008 是32bit 系统，并不能识别int64的数据类型，可能会导致一些异常。最新版本1.2.7 已经使用int32 作为参数。在这台  Galaxy J7008 android 5.1 的设备上已经可以正常使用。
