### ISSUE TITLE
写文件多写了一些空格，影响美化

### ISSUE THREAD

**Issue by whistlexie** [coder-dongjiayi/MXLogger#14]
![image](https://github.com/coder-dongjiayi/MXLogger/assets/10007354/c66d5f52-b9a3-4c84-a410-a7c4c5a78fd8)

mmap 写文件，写了一些空格进去


**Comment by coder-dongjiayi** [comment]
这看起来是我demo里面的代码，仅作为演示而已。我不太懂你说的空格是哪里。
