### ISSUE TITLE
TestFlight包崩溃

### ISSUE THREAD

**Issue by mml237** [coder-dongjiayi/MXLogger#16]
复现步骤：
1. 打开退出app时清除过期日志开关（`shouldRemoveExpiredDataWhenTerminate` = true）
2. 打包上传至TestFlight
3. TestFlight包退出应用时，系统会提示该app已崩溃，是否分享崩溃记录

**Comment by coder-dongjiayi** [comment]
> 复现步骤：
> 
> 1. 打开退出app时清除过期日志开关（`shouldRemoveExpiredDataWhenTerminate` = true）
> 2. 打包上传至TestFlight
> 3. TestFlight包退出应用时，系统会提示该app已崩溃，是否分享崩溃记录

是上传tf才崩溃 自己本地不会崩溃？ 是否有崩溃日志或者调用栈可以提供

**Comment by mml237** [comment]
补充: 
1. sdk是最新版本
2. 开启这两个开关后，TestFlight包崩溃：shouldRemoveExpiredDataWhenTerminate=true & shouldRemoveExpiredDataWhenEnterBackground=true。将其置为false后，崩溃消失
3. 仅在强退app时，TestFlight包才会提示崩溃。本地包不会，因为本地包系统不会尝试共享崩溃记录

崩溃记录：
![image](https://github.com/coder-dongjiayi/MXLogger/assets/22297921/fd01537b-e0dc-413d-a490-5df48a952ed6)
![image](https://github.com/coder-dongjiayi/MXLogger/assets/22297921/b7dcb697-ab33-470c-941b-0f858ceea744)
![IMG_7007](https://github.com/coder-dongjiayi/MXLogger/assets/22297921/adf77346-a630-4434-8afd-f1e565b80584)
dc73-3ef8-4c3b-8bb8-6b98f934beb5)

**Comment by mml237** [comment]
> 设置 隐私与安全 分析与改进 分析数据，里面有没有崩溃日志，如果有的话 请发我一下

[YMjgC62scDHr6FeikRH7M.xccrashpoint.zip](https://github.com/coder-dongjiayi/MXLogger/files/12239141/YMjgC62scDHr6FeikRH7M.xccrashpoint.zip)

**Comment by coder-dongjiayi** [comment]
也许是 shouldRemoveExpiredDataWhenTerminate=true 这个有问题，你可以先把这个属性设置为false。我尽量这周解决。
这个shouldRemoveExpiredDataWhenEnterBackground 应该是没有问题。可以为true

**Comment by coder-dongjiayi** [comment]
@mml237 shouldRemoveExpiredDataWhenTerminate这个字段新版版去掉了。
遇到任何问题欢迎反馈。
