### ISSUE TITLE
是否需要暴露flush方法？

### ISSUE THREAD

**Issue by mml237** [coder-dongjiayi/MXLogger#17]
据了解，mmap机制的同步时机为：
* 调用 msync 函数主动进行数据同步（主动）。
* 调用 munmap 函数对文件进行解除映射关系时（主动）。
* 进程退出时（被动）。
* 系统关机时（被动）

那么如果我有个上传日志的需求，是否需要在上传日志前调用flush方法，确保内存中的数据全部写入到文件中？

**Comment by coder-dongjiayi** [comment]
> 

不需要再上传日志的时候调用flush。

据我测试 这个方法大概率用不到，只有一些极端情况下有可能遇到，比如果 你程序预测到下一个瞬间手机可能没电要关机了，你可以flush 一下，确保内存数据写入磁盘。再比如说 内核突然挂了。。。目前在ios和android平台 我觉得你不用不到这个方法。

**Comment by coder-dongjiayi** [comment]
加个微信吧，有啥问题直接微信我： Mr_Dongjiayi
