### ISSUE TITLE
请问有上报log的api吗

### ISSUE THREAD

**Issue by philos3** [coder-dongjiayi/MXLogger#2]

**Comment by coder-dongjiayi** [comment]
目前MXLogger 只负责写入日志和解析日志，MXLogger 通过diskCachePath 暴露出日志文件夹的路径。具体上报时机和上报地址应该由业务决定

**Comment by philos3** [comment]
上报因为是异步，可以copy log文件之后上传。但是上传成功后，如果需要清除已经上报的log，目前只有removeExpireData和removeAll，是否可以提供一个removeBefore清除上传时间点之前的log呢

**Comment by philos3** [comment]
required String nameSpace,
      required String directory,
      String? storagePolicy,
      String? fileName,
      String? cryptKey,
      String? iv
这些是否可以增加注释，diskCachePath是directory+fileName？

**Comment by coder-dongjiayi** [comment]
> 上报因为是异步，可以copy log文件之后上传。但是上传成功后，如果需要清除已经上报的log，目前只有removeExpireData和removeAll，是否可以提供一个removeBefore清除上传时间点之前的log呢

SDK不知道什么时候业务会上报日志，因此不会有removeBefore方法。根据你的提问 可以根据现有api达到你的目的，如下：
通过 diskCachePath 获取到日志文件夹，然后遍历里面的每一个文件获取到对应的信息(文件名、创建时间、最后更新时间等等) 然后在你的业务里面记录这些。在上报成功之后根据你上报的文件名去匹配刚才你业务里面记录的文件信息，通过原生api删除对应的文件

**Comment by coder-dongjiayi** [comment]
> 

关于注释问题给你造成了困惑，我会在之后的版本细化注释。因为一次api的改动会引起ios  android flutter 三个端的变化，有时候懒了就没有写。

**Comment by philos3** [comment]
log同一个filename的应该都在同一个文件吧？？遍历里面的每一个文件获取到对应的信息(文件名、创建时间、最后更新时间等等) ？是保存多个文件吗，那逻辑是如何的呢，是否存在这种情况，我上传的时候，log写入的是a文件，但是a文件仍然在持续写入，上传完毕之后，我需要删除a上传之前的log，应该不是删除整个文件。如果上层处理，直接覆盖（remove？），那肯定会丢掉覆盖成功之前的log。

或者能否提供一个类似newAndcopy这样的api，传入copy之后的文件名，在重命名已有log文件名的时候，新的log写入到新创建的文件。我直接操作文件是否会出现

**Comment by coder-dongjiayi** [comment]
> log同一个filename的应该都在同一个文件吧？？遍历里面的每一个文件获取到对应的信息(文件名、创建时间、最后更新时间等等) ？是保存多个文件吗，那逻辑是如何的呢，是否存在这种情况，我上传的时候，log写入的是a文件，但是a文件仍然在持续写入，上传完毕之后，我需要删除a上传之前的log，应该不是删除整个文件。如果上层处理，直接覆盖（remove？），那肯定会丢掉覆盖成功之前的log。
> 
> 或者能否提供一个类似newAndcopy这样的api，传入copy之后的文件名，在重命名已有log文件名的时候，新的log写入到新创建的文件。我直接操作文件是否会出现

你可以通过diskCachePath获取到一个文件夹的路径 比如说得到的结果是一个数组[xxxx/xxxxx/2022-12-14_mxlog.log,xxxx/xxxxx/22022-12-15_mxlog.log,xxxx/xxxxx/22022-12-16_mxlog.log] 那么当前正在写入的log文件一定是数组里面距离现在时间最近的那个文件也就是2022-12-16_mxlog.log，你可以直接把当前的这个文件夹打个压缩包(这个操作并不会影响数据写入) 然后上传你的压缩包，上传完成之后删除压缩包，然后获取数组中前2个元素也就是2022-12-14_mxlog.log,2022-12-15_mxlog.log （因为2022-12-16_mxlog.log是当前正在写入的日志不能删除）再通过组合拼接diskCachePath 调用原生api删除相关文件。

**Comment by philos3** [comment]
那这样就会存在重复上传的问题了，比如我有一个上传log的入口，每次点击上传一次，只能做服务端同名文件覆盖了，问题也不大，就是费流量。目前这个多文件是根据有效期还是默认一天存储。

**Comment by philos3** [comment]
diskCachePath如何获取。是directory+fileName？

**Comment by coder-dongjiayi** [comment]
> 

MXLogger 已经暴露出这个属性了，可以直接获取。至于你说的重复上传 应该不会出现吧，因为你第一次上传之后 已经删除了一些文件，只是重复了当前正在写入的这个文件，你可以在上传的时候剔除当前正在写入的这个文件，就不会有重复上传的问题。你那边是用的android端SDK么，iOS 这边注释写的比较详细，android和flutter比较少。我之后会补上。可以设置文件存储策略 storagePolicy

yyyy_MM                    按月存储
 yyyy_MM_dd              按天存储
yyyy_ww                     按周存储
yyyy_MM_dd_HH       按小时存储

**Comment by philos3** [comment]
好的，当前正在写入的这个文件也是需要的，问题不大。十分感谢🙏🙏🙏
