### ISSUE TITLE
flutter 打包在iphone上启动白屏

### ISSUE THREAD

**Issue by camelfu** [coder-dongjiayi/MXLogger#21]

**Comment by coder-dongjiayi** [comment]
如果是你自己的项目，方便把代码发上来 看一下么。

**Comment by camelfu** [comment]
自己项目，壳工程初始化，mxlog单独写的组件

**Comment by coder-dongjiayi** [comment]
> 自己项目，壳工程初始化，mxlog单独写的组件

MXLogger 我们已经使用了很长时间，没有因为mxlogger导致的白屏反馈，从目前的信息来看 无法定位问题，甚至无法确定你发生白屏的问题与mxlogger的直接关系。如果要解决问题，我需要更详细的信息，最好是能复现问题的demo。

**Comment by camelfu** [comment]
能➕个V么，13510873210
