### ISSUE TITLE
解析日志文件太慢了.

### ISSUE THREAD

**Issue by Jichao** [coder-dongjiayi/MXLogger#23]
1M左右的文件,我用的flutter linux版本的analyzer解析出来需要5分钟左右.

**Comment by coder-dongjiayi** [comment]
> 1M左右的文件,我用的flutter linux版本的analyzer解析出来需要5分钟左右.

实在抱歉，个人精力有限。解析器目前只维护mac版本的。如果你能优化欢迎pr。

**Comment by Jichao** [comment]
明白，感谢。

**Comment by suyulin** [comment]
我先一个rust 版本的解析，周末提一个PR
