### ISSUE TITLE
如何实现直接保存日志文件为.txt文件,直接打开

### ISSUE THREAD

**Issue by FOnlyJack** [coder-dongjiayi/MXLogger#24]

**Comment by coder-dongjiayi** [comment]
MXLogger的设计是保存二进制文件，并且使用专用的解析器解析二进制文件。直接存入文本的这种方式，无论是加密还是写入效率都不高，并且不安全。除了直接的可读性几乎毫无优势。所以目前不不支持这种方式，以后也不会支持。
感谢关注。

**Comment by FOnlyJack** [comment]
> MXLogger的设计是保存二进制文件，并且使用专用的解析器解析二进制文件。直接存入文本的这种方式，无论是加密还是写入效率都不高，并且不安全。除了直接的可读性几乎毫无优势。所以目前不不支持这种方式，以后也不会支持。 感谢关注。

了解了  这样如果上传给后端 后端想查看的话也得是专门的解析器吧 不方便就是

**Comment by coder-dongjiayi** [comment]
> > MXLogger的设计是保存二进制文件，并且使用专用的解析器解析二进制文件。直接存入文本的这种方式，无论是加密还是写入效率都不高，并且不安全。除了直接的可读性几乎毫无优势。所以目前不不支持这种方式，以后也不会支持。 感谢关注。
> 
> 了解了 这样如果上传给后端 后端想查看的话也得是专门的解析器吧 不方便就是

[解析代码](https://github.com/coder-dongjiayi/MXLogger/blob/main/mxlogger_analyzer/mxlogger_analyzer_lib/lib/src/analyzer_data/analyzer_binary.dart) _decode()方法。后端可以照着写，并不是很复杂。
