### ISSUE TITLE
flutter_mxlogger: ^1.2.13+1 Could not find mxlogger-1.2.12.jar

### ISSUE THREAD

**Issue by Hynsen** [coder-dongjiayi/MXLogger#26]
rt，flutter接入最新版编译报错

**Comment by coder-dongjiayi** [comment]
> rt，flutter接入最新版编译报错

没问题啊，这个jar 是可以正常下载的，你下载example试试看呢？

**Comment by Hynsen** [comment]
额，example是可以的，但是通过pub引入确实是报这个错：Could not find mxlogger-1.2.12.jar (io.github.coder-dongjiayi:mxlogger:1.2.12).
        Searched in the following locations:
            https://maven.aliyun.com/nexus/content/groups/public/io/github/coder-dongjiayi/mxlogger/1.2.12/mxlogger-1.2.12.jar

**Comment by coder-dongjiayi** [comment]
> 额，example是可以的，但是通过pub引入确实是报这个错：Could not find mxlogger-1.2.12.jar (io.github.coder-dongjiayi:mxlogger:1.2.12). Searched in the following locations: https://maven.aliyun.com/nexus/content/groups/public/io/github/coder-dongjiayi/mxlogger/1.2.12/mxlogger-1.2.12.jar 我上Maven仓库也没搜到这个jar包

我传的是这个maven  是可以搜索到的  https://central.sonatype.com/

**Comment by Hynsen** [comment]
嗯，是Maven路径设置的关系，我的默认Maven路径是https://maven.aliyun.com/nexus/content/groups/public/ 加入mavenCentral()就可以了
