### ISSUE TITLE
日志文件无法导出

### ISSUE THREAD

**Issue by Hynsen** [coder-dongjiayi/MXLogger#27]
手机本地logger无法删除、导出，貌似是没有执行权限，如下图：
dialpad_flutter.logger是自定义的日志文件夹
![881718938014_ pic](https://github.com/coder-dongjiayi/MXLogger/assets/16485314/bea9c09e-9cc4-41b5-801b-d9d2b54e4c3e)

**Comment by coder-dongjiayi** [comment]
MXLogger 会暴露出 diskcachePath 用于获取日志文件路径。
你这个问题，看起来跟MXLogger 这个日志库没有关系。

**Comment by Hynsen** [comment]
> MXLogger 会暴露出 diskcachePath 用于获取日志文件路径。 你这个问题，看起来跟MXLogger 这个日志库没有关系。

我获取到了日志文件路径，想用adb导出的时候发现不能导出，文件权限存在问题，然后我在手机本地找到了这个日志文件，想要手动分享出去也是不行，并且也不能删除掉，MXLogger在写入文件的时候是否有设置文件权限的地方呢？

**Comment by coder-dongjiayi** [comment]
> 文件

没有设置权限，你跑一下我的demo，看看能不能正常。

**Comment by Hynsen** [comment]
demo是同样的问题，不能导出，不能删除，有可能是手机的问题，试了两台手机，小米的正常，vivo的就是不行

**Comment by Hynsen** [comment]
系统分享之前试过是不行的，又在AS上试了下，也是提示权限被拒，有点莫名其妙了，这个权限是哪里加上去了呢。。
![901718968253_ pic](https://github.com/coder-dongjiayi/MXLogger/assets/16485314/c71e4d79-c300-49a4-82e2-d50400d823b7)

**Comment by Hynsen** [comment]
在这里找到了一个类似的问题，mxlogger生成log目录的时候是否也是这样的形式呢？
https://github.com/iqiyi/xCrash/issues/109#issuecomment-1241838542

**Comment by coder-dongjiayi** [comment]
> 在这里找到了一个类似的问题，mxlogger生成log目录的时候是否也是这样的形式呢？ [iqiyi/xCrash#109 (comment)](https://github.com/iqiyi/xCrash/issues/109#issuecomment-1241838542)

收到。我看一下，有结果会再次回复你。

**Comment by coder-dongjiayi** [comment]
> 在这里找到了一个类似的问题，mxlogger生成log目录的时候是否也是这样的形式呢？ [iqiyi/xCrash#109 (comment)](https://github.com/iqiyi/xCrash/issues/109#issuecomment-1241838542)

maven 暂时不能更新了，你先尝试一下 通过暴露出来的路径给日志文件打个压缩包(自定义一个路径)，看看这个压缩包能导出来么。

**Comment by Hynsen** [comment]
试了下，压缩包可以导出，但是解压后日志文件变为0字节
![911719283628_ pic](https://github.com/coder-dongjiayi/MXLogger/assets/16485314/c18f4e8e-9933-45e6-bde5-575f929c9836)

**Comment by coder-dongjiayi** [comment]
能正常通过解析工具解析日志数据么？

**Comment by Hynsen** [comment]
不行，解析工具一直卡在正在导入数据

**Comment by Hynsen** [comment]
Maven更新了么

**Comment by coder-dongjiayi** [comment]
> Maven更新了么

今天刚刚发布，等下maven同步。maven同步完成pub.dev还得同步。估计下午最晚4 5点钟就可以更新测试了。
