### ISSUE TITLE
Flutter 下iOS触发remove_expire_data会Crash

### ISSUE THREAD

**Issue by ChenShifu0308** [coder-dongjiayi/MXLogger#30]
![img_v3_02du_fdd372e8-7a93-401a-a438-d36b81d3028h](https://github.com/user-attachments/assets/27fb8751-5609-4226-9abd-6f06edcd0ecc)

**Comment by coder-dongjiayi** [comment]
是我的demo么，如果不是的话把复现的工程代码发上来。

**Comment by coder-dongjiayi** [comment]
> > > hello [@coder-dongjiayi](https://github.com/coder-dongjiayi) , 我这也出现这种情况了，iOS crash ![Image](https://github.com/user-attachments/assets/f0875498-ea27-458c-bed3-568a68c67eac)
> > 
> > 
> > 版本号，是否能重现，最好有一个能重选的demo发上来。
> 
> [@coder-dongjiayi](https://github.com/coder-dongjiayi) 版本是pub库最新的1.2.14，我没有重现出来，是线上报的crash，退后台和直接调用删除过期日志的方法都没复现出来。

这个问题以前出现过 后来被修复了，你线上这个版本对应的mxlogger的日志版本能确定么？

**Comment by itlwy** [comment]
@coder-dongjiayi 打包机这边看pubspec.lock里锁着的版本是1.2.14

**Comment by coder-dongjiayi** [comment]
> 以前出现过，是怎么复现的啊？ [@coder-dongjiayi](https://github.com/coder-dongjiayi)

在 v1.2.6 及以下版本是必现的，demo就能重现。之后的版本已经修复了，再没有反馈这个问题。

**Comment by itlwy** [comment]
那不太可能用到1.2.6的版本，我看这是2年前的版本了

**Comment by coder-dongjiayi** [comment]
> 有啥办法能让它及时出现删除异常，但是不让应用crash吗，没删除就没删除，也不影响功能~
flutter端 调用``` shouldRemoveExpiredDataWhenEnterBackground``` 这个方法把后台清理这个功能禁掉。由业务决定什么时候清理本地日志文件。在你需要的时候调用``` removeExpireData``` 方法
