### ISSUE TITLE
求助，使用MXStoragePolicyType.yyyy_MM_dd_HH的问题

### ISSUE THREAD

**Issue by itlwy** [coder-dongjiayi/MXLogger#31]
我使用MXStoragePolicyType.yyyy_MM_dd_HH策略来初始化日志库，但发现使用时，一直往同一个日志文件写，比如下午4点都时进入App进行操作，日志内容都写进2024-10-11-16_log.mx里了，但时间来到下午5点都时，我继续操作App，日志文件仍然往2024-10-11-16_log.mx里写，而不是新建一个2024-10-11-17_log.mx的日志文件。请问如何解决啊 
@coder-dongjiayi

**Comment by coder-dongjiayi** [comment]
> 我使用MXStoragePolicyType.yyyy_MM_dd_HH策略来初始化日志库，但发现使用时，一直往同一个日志文件写，比如下午4点都时进入App进行操作，日志内容都写进2024-10-11-16_log.mx里了，但时间来到下午5点都时，我继续操作App，日志文件仍然往2024-10-11-16_log.mx里写，而不是新建一个2024-10-11-17_log.mx的日志文件。请问如何解决啊 @coder-dongjiayi

这个设计的逻辑不是实时检测是否符合  yyyy_MM_dd_HH的策略,只有重启App的时候,或者说重新初始化logger的时候才会去检测是否符合yyyy_MM_dd_HH的策略。
比如:
下午4点的时候写入日志 为2024-10-11-16_log.mx。在没有重新logger的情况下依然会往2024-10-11-16_log.mx 这个文件里面继续写。只有杀掉进行重启app的时候检测yyyy_MM_dd_HH的策略 如果此时是下午5点那么就会创建2024-10-11-17_log.mx这个文件。

**Comment by navyzhou926** [comment]
> > 我使用MXStoragePolicyType.yyyy_MM_dd_HH策略来初始化日志库，但发现使用时，一直往同一个日志文件写，比如下午4点都时进入App进行操作，日志内容都写进2024-10-11-16_log.mx里了，但时间来到下午5点都时，我继续操作App，日志文件仍然往2024-10-11-16_log.mx里写，而不是新建一个2024-10-11-17_log.mx的日志文件。请问如何解决啊 @coder-dongjiayi
> 
> 这个设计的逻辑不是实时检测是否符合 yyyy_MM_dd_HH的策略,只有重启App的时候,或者说重新初始化logger的时候才会去检测是否符合yyyy_MM_dd_HH的策略。 比如: 下午4点的时候写入日志 为2024-10-11-16_log.mx。在没有重新logger的情况下依然会往2024-10-11-16_log.mx 这个文件里面继续写。只有杀掉进行重启app的时候检测yyyy_MM_dd_HH的策略 如果此时是下午5点那么就会创建2024-10-11-17_log.mx这个文件。



我设置为yyyy_MM_dd模式保存日志时（想要一天的日志都保存到同一个文件中）。在同一天，每次我重新启动App并MXLogger.initialize初始化后，当天的日志文件（2024-10-30_log.mx）就只保存本次登录后的各种写入日志，在同一天之前重新启动登录的日志就被覆盖掉了

**Comment by coder-dongjiayi** [comment]
> > > 我使用MXStoragePolicyType.yyyy_MM_dd_HH策略来初始化日志库，但发现使用时，一直往同一个日志文件写，比如下午4点都时进入App进行操作，日志内容都写进2024-10-11-16_log.mx里了，但时间来到下午5点都时，我继续操作App，日志文件仍然往2024-10-11-16_log.mx里写，而不是新建一个2024-10-11-17_log.mx的日志文件。请问如何解决啊 @coder-dongjiayi
> > 
> > 
> > 这个设计的逻辑不是实时检测是否符合 yyyy_MM_dd_HH的策略,只有重启App的时候,或者说重新初始化logger的时候才会去检测是否符合yyyy_MM_dd_HH的策略。 比如: 下午4点的时候写入日志 为2024-10-11-16_log.mx。在没有重新logger的情况下依然会往2024-10-11-16_log.mx 这个文件里面继续写。只有杀掉进行重启app的时候检测yyyy_MM_dd_HH的策略 如果此时是下午5点那么就会创建2024-10-11-17_log.mx这个文件。
> 
> 我设置为yyyy_MM_dd模式保存日志时（想要一天的日志都保存到同一个文件中）。在同一天，每次我重新启动App并MXLogger.initialize初始化后，当天的日志文件（2024-10-30_log.mx）就只保存本次登录后的各种写入日志，在同一天之前重新启动登录的日志就被覆盖掉了

把你这个问题的demo 打个zip发上来，我看下。

**Comment by navyzhou926** [comment]
[mxloggertest.zip](https://github.com/user-attachments/files/17581133/mxloggertest.zip)

**Comment by navyzhou926** [comment]
> [mxloggertest.zip](https://github.com/user-attachments/files/17581133/mxloggertest.zip)

@coder-dongjiayi demo已经上传

**Comment by coder-dongjiayi** [comment]
> > [mxloggertest.zip](https://github.com/user-attachments/files/17581133/mxloggertest.zip)
> 
> @coder-dongjiayi demo已经上传

已经确认问题，不知道什么时候改错了。修复这个bug之后 我会再回复你

**Comment by coder-dongjiayi** [comment]
> [mxloggertest.zip](https://github.com/user-attachments/files/17581133/mxloggertest.zip)

已经发了新版 v1.2.14 过一会pub.dev上更新了你再试试。

**Comment by navyzhou926** [comment]
> > [mxloggertest.zip](https://github.com/user-attachments/files/17581133/mxloggertest.zip)
> 
> 已经发了新版 v1.2.14 过一会pub.dev上更新了你再试试。

测试后，没有问题了
